### ISSUE TITLE
Problems with the work of Aria2 in the smartphone

### ISSUE THREAD

**Issue by pac20** [Alexander--/aria2-android#12]
Hi developers.Sorry for my english.I will try to describe the problems as detailed as possible.
But I warn that I'm not advanced by the user but a little knowledgeable.
1)I had to resort to testing both the anroid version and the PC version Aria2.
PC version :
Testing was carried out through downloading the folder from the cloud storage.
To analyze the download process on the smartphone, the port scanner application was downloaded.
After launching the download folder on the PC on the smartphone, the ports were checked for openness.
IP address 127.0.0.1 (localhost) - port 6800 - open
IP address Local ip PC - port 6800 - open
IP address smarphone - local  ip - port 6800 - clouse (aria2 was not started)
IP address Internet ip - port 6800 - open
For 100% confidence was checked on several sites the openness of the port 6800.
Sites report the port 6800 is open.
The folder was downloaded.
Anroid version :
Testing was carried out through downloading the torrent.
But I will make a reservation.
On the smartphone to download torrents I used utorrent.In utorrent there is such an interesting thing.
When the application is installed, it already contains the default folder for downloading torrents.
Which can not be changed but from which you can transfer the downloaded to where you need it.
In Aria2 for android also done.But access to content is closed.
Testing produced in two applications is in Aria2 and Aria2App.
Aria 2 was used to run Aria2 RPC server
Aria2App for torrent download
I tried many times to launch the download and there was always a download speed of 0.
But one day I somehow started it all.And I naturally began to check everything.
When the beginning of the swing I began to check the ports.
IP address 127.0.0.1 (localhost) - port 6800 - open
IP address Local ip PC - port 6800 - clouse (aria2 was not started)
IP address smarphone - local  ip - port 6800 - open
IP address Internet ip - port 6800 - clouse
For 100% confidence was checked on several sites the openness of the port 6800.
Sites report the port 6800 is clouse.
But nevertheless downloading went.But the truth at the time of the download were the disconnections (15 or 20 seconds of downloading and breaking) between the applications as I'm guessing.But due to the fact that in Aria2App there is a function of restoring the connection, the connection was restored.
After downloading the access to the torrent, I did not get it.I deleted everything by resetting the application settings.
And on the above, I have questions for you.
How could it be that the port in the local network is open and on the Internet is closed and generally how everything could download?
I've installed more Aria2Android around your application.And in Aria2Anroide in the download folder it is impossible to write.
You tried to change the download folder but nothing left?Is it really connected with SAF?
While writing the download again started up but the truth Internet IP on the port of information is no, but the site says that the port is open.
And when adding a torrent to the Aria2 WebUI it is written that there is no connection with the ARIA2RPC server
I tried everything and reset the phone settings and hard reset.
2)If you think that everything is in the firmware of the smartphone, then if you need the firmware itself, I can give it to you.
After answering the questions, please do not close the topic as there is still a question.
Smartphone from which I'm testing Prestigio muze b3 chipset MT6580 (32bit) 1gb random access memory and memory card is integrated in the system.System Android 6.0 no root.

**Comment by Alexander--** [comment]
> How could it be that the port in the local network is open and on the Internet is closed

NAT?

> But nevertheless downloading went.But the truth at the time of the download were the disconnections (15 or 20 seconds of downloading and breaking)

This is covered in aria2-android [FAQ](http://aria2-android.sourceforge.net/faq/): if the download is expected to be long (longer than couple of seconds), try to enable a wakelock before starting it (and make sure to stop aria2-android after download completes).

> the download folder it is impossible to write

Then chose a different, writable folder in aria2-android settings.

> Is it really connected with SAF?

Maybe.

> I tried everything and reset the phone settings and hard reset.

Removing/reinstalling aria2-android should be enough. aria2-android does not make any lasting changes to your system, so wipe/hard reset does not make difference, compared to deinstallation.

**Comment by Alexander--** [comment]
Also please note, that changes to aria2 settings, made by aria2-android, take effect only after the process is restarted (e.g. after you press the green toggle).

**Comment by pac20** [comment]
About NAT servers.
Yes I tested the connections for open / closed port 6800.And there were incomprehensibilities as you can see from my post.

with the download folder figured out.not correctly pointed out the path.

**Comment by pac20** [comment]
I found how to swing through the firefox  on.I'm testing.

**Comment by Alexander--** [comment]
> Yes I tested the connections for open / closed port 6800.And there were incomprehensibilities as you can see from my post.

Could you elaborate? This sounds like typical description of [NAT](https://wikipedia.org/wiki/NAT)-ed network device for me. What exactly do you think is incomprehensible?

> with the download folder figured out.not correctly pointed out the path.

Manually changing the path is a kind of pain. Created #13
