### ISSUE TITLE
Problems with downloading torrent in Aria2 WebUI

### ISSUE THREAD

**Issue by pac20** [Alexander--/aria2-android#14]
There is a problem with downloading torrent in Aria2 WebUI.
The problem is that when adding torrent to Aria2 WebUI it is reported that there is no connection with Aria2 RPC ( a memory card is integrated in the system Android 6.0 ).
Trying in Connection Settings register 127.0.0.1 does not lead to anything.
At the same time, when adding torrent to Aria2App, then further work is successful.
Developers with what it may be related to?
And there is a second problem.
If you set your parameters in the Global Settings, then the parameters are changed to the current session and are not saved in the future.

**Comment by Alexander--** [comment]
> The problem is that when adding torrent to Aria2 WebUI it is reported that there is no connection with Aria2 RPC

Yes, this may happen. The bundled WebUI is still half-experimental — you might get better experience with Transdroid and other standalone clients.

Running WebUI in built-in WebView (e.g. inside aria2-android) usually works fine, but it might not properly react to changed password. Make sure, that you **set aria2 password in webui settings**.

Running in separate browser (e.g. Firefox/Chrome from `file://` scheme) might result in lost cookies (WebUI stores settings in cookies) and other unplesant stuff. This is fallback mode, better try Transdroid instead.

**Comment by pac20** [comment]
Alexander
Ok.I run without a token in Aria2 WebUI. I'll try.
With token no run.Sadness.
For the sake of experiment I try through access from outside.

**Comment by pac20** [comment]
During access from outside works. I tried in webui-aria2 on PC.

**Comment by Alexander--** [comment]
@pac20 

Did setting the token work?

> During access from outside works. I tried in webui-aria2 on PC.

Please add more details. What are you trying to accomplish now and what does not work?

**Comment by pac20** [comment]
Здраствуй Александр давно с тобой не списывались.
Есть одно деловое предложение.Необходимо создать праздничную открытку которая при нажатие на кнопку принятия могла бы добавлять человека в группу и рассылаться его кругу общения.Такое вообще возможно?И в какую сумму обойдётся?
