### ISSUE TITLE
New maintainer wanted

### ISSUE THREAD

**Issue by Alexander--** [Alexander--/aria2-android#17]
I am currently busy with various matters, and development of this project has stagnated a little too much. If you feel like lending a hand, leave a comment in this issue, and we will discuss details.

**Comment by niveuseverto** [comment]
I can give a hand or two ;)

Want to add aria2 as download manager to private project so I'm interested.

**Comment by Alexander--** [comment]
@niveuseverto 

I'd like to discuss this using more interactive channel — tell me your availability hours so we could have a chat in [Gitter](https://gitter.im/aria2-android/Lobby).

**Comment by dasbiswajit** [comment]
I am looking forward to it.

**Comment by niveuseverto** [comment]
@Alexander-- joined Gitter, ping me there.
