### ISSUE TITLE
Can't connect from different device

### ISSUE THREAD

**Issue by FezVrasta** [Alexander--/aria2-android#4]
Hi, thank for the app!

I'm trying to use it to convert my Nvidia Shield Android TV into a torrent box.

I managed to install it and I could connect with Transdrone from my nvidia.

When I try to connect to it from my smartphone, the transdrone app returns a connection problem.

I tried to change the aria 2 addres from localhost to the nvidia shield IP but the problem persist.

Are you aware of a solution?

**Comment by Alexander--** [comment]
Thanks for your feedback. This appears to be a highly-demanded feature. I will do my best to implement it shortly (probably should be ready by the end of this week). Could you try finding the aria2 config file (it should be somewhere in the download directory) and manually append `rpc-listen-all=true` to it?

**Comment by FezVrasta** [comment]
Thanks for the quick reply! I'm going to try today and I will let you know.

**Comment by FezVrasta** [comment]
Adding that option it works, I mean, it allows me to connect to Aria from a smartphone.

I tried adding a torrent but it just hangs there forever (and the whole Shield becomes unresponsive and laggy). But it's a different issue, I'll open a new one.

**Comment by Alexander--** [comment]
Version 0.12 added support for enabling `rpc-listen-all` from UI (it also checks that secret token is set, just in case). Closing.
