### ISSUE TITLE
Certificate support for http downloads

### ISSUE THREAD

**Issue by Alexander--** [Alexander--/aria2-android#5]

**Comment by wicast** [comment]
I think this pipe will help.
 https://github.com/chdir/aria2-android/blob/master/README.md
cat /etc/security/cacerts/* | aria2c --ca-certificate=/proc/self/fd/0

**Comment by Alexander--** [comment]
Interesting, thanks for the information. Unfortunately, the specified location does not account for removed (compromised) CAs, so security benefits of such hack are FOOBAR.

Personally I would prefer to dynamically download CAs from a trusted source and keep them up to date using a scheduled background Service (like most Android browsers do). Patches welcome.
