### ISSUE TITLE
Available space doesn't change when I change directory

### ISSUE THREAD

**Issue by FezVrasta** [Alexander--/aria2-android#6]
I configured an external hard disk and created a directory as `/Android/data/net.sf.aria2/files/aria2Downloads` (if it's wrong is a typo, I've not my Shield here right now).

The external hard disk has 1tb of space, but Aria2 tells me that there are only 8gb free (this is the available space of the internal memory tho!)

What's wrong?

**Comment by Alexander--** [comment]
@FezVrasta I will try to reproduce the issue shortly.

**Comment by Alexander--** [comment]
I don't have a SHIELD device, but I tried to reproduce an issue on emulator by creating a 10Gb SD card image (9.9Gb available) and switching between it and external storage (600Mb available). Everything worked as intended. I also double-checked the code, and it is calculating the space correctly. Are you sure that you have switched to directory on external partition? Not just "external sdcard" physically locating inside the device? Does restarting the app process resolve the issue or is it always showing the space incorrectly?
