### ISSUE TITLE
Torrents don't start downloading

### ISSUE THREAD

**Issue by FezVrasta** [Alexander--/aria2-android#7]
So, my setup is an NVidia SHIELD with an external hard drive connected (ExFat).

When I try to download any torrent, it's listed in the downloads, but the download never starts.
The same torrent works fine on my Mac with Transmission.

Also, when a torrent is added, the whole Android UI becomes unresponsive and laggy, it also restarted itself once.

**Comment by Alexander--** [comment]
You haven't specified your client application and Android version. Are you using WebUI? Can you install Android Terminal Emulator and look at aria2 console output? Note, that WebUI has tendency to overload weak devices by frequently sending huge requests to aria2 server. You may want to try out a couple of other clients and look if that fixes the lag.

**Comment by FezVrasta** [comment]
I tried both with Transdrone (both locally and remotely on a different phone) and also through http://ziahamza.github.io/webui-aria2/

Sorry I'm not an Android expert, where can I find the LogCat?

**Comment by Alexander--** [comment]
LogCat can be viewed by specialized tools on rooted devices. Don't bother with it for now — install [Android Terminal Emulator](https://play.google.com/store/apps/details?id=jackpal.androidterm&hl=en) and check the ATE integration checkbox in "frontend" section of aria2. You should be able to view aria2 output in the terminal after switching to the ATE window. Please do so and let me know if it contains anything useful.

**Comment by Alexander--** [comment]
I have filed [an issue](https://github.com/erickok/transdroid/issues/347) on Transdroid tracker to reduce the size of RPC queries. Hopefully, this should have positive impact on system responsiveness when using Transdroid with aria2.

Regarding aria2-webui — please don't use the version from upstream developer it has [known](https://github.com/ziahamza/webui-aria2/issues/142) [bugs](https://github.com/ziahamza/webui-aria2/issues/193) resulting in high CPU usage. The latest build of aria2 includes the modified version of aria2-webui that reduces frequency of RPC queries. You can find it in "frontend" section of the app.

Please install Android Terminal Emulator and check aria2 output. I can not debug your issue without ensuring that aria2 itself is configured and operating normally.

**Comment by FezVrasta** [comment]
I'll try to give you more info today, thank you!

**Comment by ghost** [comment]
Not much useful debug output. Looking for request more seeds. There's so many trackers for the test torrents and if one is blocked giving output no address associated with hostname can't it go on to the next?

**Comment by Alexander--** [comment]
@mercenaryship Sorry for long delay, — for some reason I haven't seen your comment. Such issues should be reported to [aria2 bugtracker](https://github.com/aria2/aria2/issues). I don't modify aria2 output, shown in Terminal Emulator.

If the messages, displayed in popups weren't helpful, that should be fixed in the next version.

**Comment by Alexander--** [comment]
This issue has been open for long time with no useful feedback. I have just checked with version 0.12, and torrents are downloading just fine for me. If anyone have relevant information to add (logfiles, aria2 terminal output, details concerning failed torrents), they should post it here and ask to reopen. Closing.
