### ISSUE TITLE
Questions about setting up aria2 for Android

### ISSUE THREAD

**Issue by pac20** [Alexander--/aria2-android#9]
Здравствуйте Александр.Я скачал приложение на маркете.Как я понимаю это уже рабочее приложение т.е оно не требует установку через adb  для андройд но правда в бэта-тестирование.Как я понял aria2 rpc работает только в web интерфейсе приложения и её невозможно пока использовать в других браузерах я верно понял описание в маркете?Когда я установил первый раз приложение то у меня не возникло проблем с запуском web интерфейса в Яндекс браузере .Но потом недоосмыслив что это рабочая ариа для андройд я удалил её. Поняв что она работает опять скачал.Но сейчас файл index.html не открывается в браузере.В папке /data/ пусто но я не удивляюсь т.к смартфон у меня не рутирован.Что сможете посоветовать сделать?Может хард ресерт сделать.Aria2 собственно нужна для пользования в Облачном хранилище Байду.У Байду в облаке просто есть такая фишка что если пользователь авторизирован в облаке то Байду free пользователям предоставляют низкую скорость скачивания.А если у себя в облаке сделать общедоступной для скачивания папку и выйти из облака то скорость скачивания будит согласно тарифу провайдера.Собственно для этого и необходима Ариа2.Я просто сейчас тестирую облако на андройде.И предпологаю пользоваться облоком в андройд версии.Буду ждать от вас новостей.

**Comment by pac20** [comment]
то Байду free пользователям предоставляют низкую скорость скачивания.А если у себя в облаке сделать общедоступной для скачивания папку и выйти из облака то скорость скачивания будит согласно тарифу провайдера.Собственно для этого и необходима Ариа2.Я просто сейчас тестирую облако на андройде.И предпологаю пользоваться облоком в андройд версии.Буду ждать от вас новостей.

**Comment by pac20** [comment]
И ещё не могли бы вы собрать какой нибудь apk или дополнение к браузеру для создания ссылок на скачивание для Aria2 для какого нибудь браузера андройда.

**Comment by Alexander--** [comment]
Здравствуйте, Павел. 

> И ещё не могли бы вы собрать какой нибудь apk или дополнение к браузеру для создания ссылок на скачивание для Aria2 для какого нибудь браузера андройда.

Попробую, но боюсь, что удастся этим заняться не раньше следующего месяца. Создал https://github.com/chdir/aria2-android/issues/10

> Как я понял aria2 rpc работает только в web интерфейсе приложения и её невозможно пока использовать в других браузерах я верно понял описание в маркете?

Нет, вы не совсем верно поняли. Но сначала давайте определимся с терминологией.

aria2 — консольное приложение (исполняемый файл называется `aria2c`). aria2-android — написанная мной обёртка, облегчающая его запуск на Android. aria2-webui ­— один из графических интерфейсов для aria2 (сделанный в виде веб-страницы).

aria2-android включает в себя как исполняемый файл aria2, так и aria2-webui (запускающийся прямо внутри aria2-android или в браузере на устройстве — на выбор). Т.е. aria2-adndroid включает всё что нужно чтобы качать торенты с Android-устройства. Но использовать встроенный aria2-webui необязательно. Можно использовать и любой другой графический интерфейс: 
отдельный aria2-webui на Android-устройстве, aria2-webui по сети, Transdroid  и т.д. Достаточно только указать в графическом интерфейсе адрес для подключения (localhost или IP устройства), порт и пароль.

> Поняв что она работает опять скачал.Но сейчас файл index.html не открывается в браузере.

Вы запускаете через aria2-android? Фронтенд -> Открыть WebUI?

> В папке /data/ пусто

Всё верно, aria2-android хранит исполняемый файл `aria2c` в другом месте; без root вы его не сможете увидеть.

**Comment by pac20** [comment]
Вы запускаете через aria2-android? Фронтенд -> Открыть WebUI?
Да я запускал через выше указанное при этом у меня стояли галочки в Использовать браузер и Доступ из вне.Всё согласно вашим комментариям в маркете.Когда у меня в выборе сети стоит Позволять Ариа2 сделать выбор то в терминале идёт соединение по ipv4 и ipv6.Если я выставляю в выборе сети использовать указанный интерфейс и прописываю локальный адрес смартфона то в терминале ipv4 error а ipv6 идёт соединение.Почему всё так.

**Comment by pac20** [comment]
И по поводу создания или apk или дополнения к мобильному браузеру вам рекомендую ознакомиться с этим https://github.com/acgotaku/BaiduExporter .И оставляю вам ссылку на мою расширенную папку в облаке Байду https://pan.baidu.com/s/1i5BxmaL
Дело в том что когда я пытаюсь через Хром на андройде с неё что либо качать то в полной версии браузера всё качает браузер с низкой скоростью.Если перейти на wap версию то предлагается скачивание через клиента байду.На ПК я тестировал AirExplorer и Aria2 и только они успешно справлялись со скачиванием на скорости от провайдера.Я вас не тороплю и готов денежно поощирить.Поймите правильно платить 40$ в год за 5ТБ и при этом за высокую скорость конечно не каждый в состоянии.А тем более учитывая как стремительно растёт сфера разработки все различного софта и игровых технологий то объёма в 5ТБ может не на долго хватить.И если вам интересно то могу с вами поделиться инфой по поводу облака Байду.
У меня с запуском Ариа2 всё получилось в Aria2App всё запустилось правда в Браузере Хроме не хочет открываться не удаётся получить доступ к сайту ERR_INVALID_RESPONSE

**Comment by pac20** [comment]
И ещё в Uget в настойках требуется ввести путь к Aria2.Не подскажите какой путь должен быть?Заранее благодарю вас за оперативность и за разъяснения.С вами приятно как и общаться так и иметь дело.

**Comment by pac20** [comment]
В браузере указывал как localhost:6800 так и локальный адрес:6800 .В https пишет разорвано соединение.

**Comment by Alexander--** [comment]
Отвечу в чате.

**Comment by Alexander--** [comment]
Created #10, #11 and others per discussion in chat. Closing.
